name: Build and Test .NET 4.8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8.x'

    - name: Restore dependencies
      run: |
        nuget restore ISBNQuery.sln

    - name: Build
      run: |
        msbuild /p:Configuration=Release ISBNQuery.sln

    - name: Test
      run: |
        # Execute seus testes aqui

    - name: Publish artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          ISBNQuery/bin
